title: Ben's Website
email: me@bgertz.com
author: Benjamin Gertz
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website. It is a work in progress but live for viewers like you.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://www.bgertz.com/" # the base hostname & protocol for your site, e.g. http://example.com
#theme: minima
remote_theme: daviddarnes/alembic
url: 'https://bgertz.com'
baseurl: ''

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# social: # jekyll-seo-tag > social overrides
#   name: Ben Gertz # jekyll-seo-tag > real name
#   links:  # jekyll-seo-tag > social aliases (sameAs)
#     - https://www.linkedin.com/in/benjamin-gertz/
#     - https://github.com/bgert

github_username:  bgert


# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
#- title: About
#  url: /about/
- title: Blog
  url: /blog/
- title: Resume
  url: /resume/
- title: Don't click me
  url: /clickme/
# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "My thoughts and ideas"
    # feature_text: |
    #   Welcome to my blog
    feature_image: "https://raw.githubusercontent.com/bgert/bgert.github.io/master/new_street_car.jpg"
