title: Ben's Website
email: me@bgertz.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website. It is a work in progress but live for viewers like you.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://www.bgertz.com/" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: benjamin-gertz
github_username:  bgert
theme: jekyll-theme-minimal